class SOPHIAConstants:
    SOPHIA_PROCESS_HTTP_LINK = ' HTTPLINKCONS ' 
    SOPHIA_PROCESS_HTTP_LINK_REGULAR = '([a-zA-Z]+\d+)|(\d+[a-zA-Z位]+)|' \
                                    '(\\\{0,}[\d+,\.‐:/-]{2,})|' \
                                    '([\w+_\d+/]+\.com)|([\w+_\d+/]+\.docx)|([\w+_\.\d+/]+\.doc)|([\w+_\d+/]+\.xlsx)|([\w+_\d+/]+\.pdf)|([\w+_\d+/]+\.xml)|([\w+_\d+/]+\.json)|([a-zA-Z_\d+/]+\.java)|' \
                                    '([a-zA-Z0-9\.\+\-_]+\@\w+\.[a-z]{0,}\.{0,}[a-zA-Z]{0,}\.{0,}[a-zA-Z]{0,}\.{0,}[a-zA-Z]{0,})|' \
                                    '([Hhttpf]+s?:/+(?:[a-zA-Z0-9$\-_@.&+!*,/:\?=]|(?:%/[a-zA-Z0-9]))+)|([Hhttpf]+s?:/+(?:[a-zA-Z0-9$\-_@.&+!*,/]|(?:%*/[0-9a-zA-Z]))+)|(www\.(?:[a-zA-Z0-9$\-_@.&+!*,/]|(?:%*/[0-9a-zA-Z]))+)|(\\\+\d+\.+\d+)'
    SOPHIA_PROCESS_NUMBER_REGULAR = '(?<=\d)(\s)([.,]+)(\s)(?=\d)'
    SOPHIA_MECAB_TAG = '-Owakati' #''mecabrc'
    SOPHIA_EOS_TAG = 'EOS'
    SOPHIA_READ_CSV_SEP = 'SOPHIA_READ_CSV_SEP_CONS'
    SOPHIA_READ_CSV_SEP_COL_SAMPLE = 'sample'
    SOPHIA_WORD_NOTHING = 'nothing'
    SOPHIA_CHAR_NFC = 'NFC'
    SOPHIA_CHAR_NFKC = 'NFKC'
    SOPHIA_CHAR_CODE_UTF8 = 'utf-8'


    SOPHIA_CHAR_SPECIAL_PATTERN_SYMBOL_2 = u'[?!。]*[?!。]'
    SOPHIA_CHAR_SPECIAL_PATTERN_SYMBOL_VIJA_2 = u'[?!. ]*[?!. ]'

    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_2 = '(?<=\d)(\s)([a-zA-Z])' # vd:  300 N -> 300N
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_1 = '([a-zA-Z])(\s)(?=\d)' # e 300 -> e300

    SOPHIA_CHAR_SPECIAL_PATTERN_NUMBER_2 = '(?<=\d)(\s)([.,])(\s)(?=\d)' # 1 , 2 -> 1,2

    SOPHIA_CHAR_SPECIAL_PATTERN_CURRENCY = '(?<=\d)(\s)([.%$£°])'
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_OTHER = '(?<=\S)(\s+)([.,:;?!>/／)\]\」』】〕#%*_~\-\}])'  # abc , -> abc,
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_OTHER_2 = '([／\/#*_\-~<])(\s)(?=\S)' # sua abc / xyz -> abc/xyz
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_3 = '((?<=")(\s)(.*?)(\s)(?="))' # " abc " -> "abc"
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_4 = '([\({\[\<「『【〔])(\s)(?=\S)'

    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_5 = '([\.。]$)|([\.。]\s+$)|(\s+[\.。]$)'    
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_R5 = r'(\.+$)|(\.\s+$)|(\。+$)|(\。\s+$)'  
    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_R5_ja = r'(\。+$)|(\。\s+$)'

    SOPHIA_CHAR_SPECIAL_PATTERN_ALPHABET_6 = '(\w)(\s)(\')(\s)(\w)' #  can ' t -> can't
    SOPHIA_CHAR_SPECIAL_PATTERN_R_6 = r'\1\3\5'

    SOPHIA_CHAR_SPECIAL_PATTERN_R_3 = r'\3'
    SOPHIA_CHAR_SPECIAL_PATTERN_R_2 = r'\2'
    SOPHIA_CHAR_SPECIAL_PATTERN_R_1 = r'\1'
    SOPHIA_CHAR_SPECIAL_PATTERN_R_0 = r''

    SOPHIA_CHAR_SPECIAL_PATTERN_EMPTY_STRING = ' '

    #============================== FOR INFER unknow process
    SOPHIA_INFER_TAG_unk_sr = '<unks%s>'
    SOPHIA_INFER_TAG_unk_tg = '<unkt%s>'
    SOPHIA_INFER_TAG_unk_num = '<num%s>'
    SOPHIA_INFER_TAG_prefix_sr = '<unks>'
    SOPHIA_INFER_TAG_prefix_tg = '<unkt>'
    SOPHIA_INFER_TAG_prefix_num = '<num>'
    SOPHIA_INFER_TAG_prefix_unkt = '<unkt'

    PROCESS_VI_TO_EN = 'vien'


class UNKNOWN:
        
        UNK_SRC = "<unks%s>"
        UNK_TG = "<unkt%s>"
        UNK_NUM = '<num%s>'
        UNK_TERM = '<term%s>'
        PREFIX_SRC = '<unks>'
        PREFIX_TG = '<unkt>'
        PREFIX_NUM = '<num>'
        PREFIX_TERM = '<term>'
class NAME:
    POS_name = {
        "việt nam":"Việt Nam",
        "Việt nam":"Việt Nam",
        "vietnamese":"Vietnamese",
        "thái lan":"Thái Lan",
        "Thái lan":"Thái Lan",
        "lào":"Lào",
        "myanmar":"Myanmar",
        "malaysia":"Malaysia",
        "philippines":"Philippines",
        "indonesia":"Indonesia",
        "cambodia":"Cambodia",
        "combodia":"Combodia",
        "đông timo":"Đông Timo",
        "brunei":"Brunei",
        "singapore":"Singapore",
        "nhật bản":"Nhật Bản",
        "tiếng nhật":"tiếng Nhật",
        "Nhật bản":"Nhật Bản",
        "japan":"Japan",
        "japanese":"Japanese",
        "hàn quốc":"Hàn Quốc",
        "Hàn quốc":"Hàn Quốc",
        "south korea":"South Korea",
        "South korea":"South Korea",
        "trung quốc":"Trung Quốc",
        "Trung quốc":"Trung Quốc",
        "Trung hoa":"Trung Hoa",
        "trung hoa":"Trung Hoa",
        "china":"China",
        "chinese":"Chinese",
        "uzebekistan":"Uzebekistan",
        "ấn độ":"Ấn Độ",
        "Ấn độ":"Ấn Độ",
        "afganistan":"Afganistan",
        "đài loan":"Đài Loan",
        "iran":"Iran",
        "iraq":"Iraq",
        "israel":"Israel",
        "jordan":"Jordan",
        "liban":"Liban",
        "mông cổ":"Mông Cổ",
        "oman":"Oman",
        "pakistan":"Pakistan",
        "qatar":"Qatar",
        "hồng kông":"Hồng Kông",
        "english":"English",
        "england":"England",
        "germany":"Germany",
        "france":"France",
        "french":"French",
        "paris":"Paris",
        "london":"London",
        "new york":"New York",
        "italia":"Italia",
        "nga":"Nga",
        "russian":"Russian",
        "ba lan":"Ba lan",
        "Ba lan":"Ba lan",
        "phần lan":"Phần Lan",
        "Phần lan":"Phần Lan",
        "thụy sĩ":"Thụy Sĩ",
        "Thụy sĩ":"Thụy Sĩ",
        "thụy điển":"Thụy Điển",
        "Thụy điển":"Thụy Điển",
        "tây ban nha":"Tây Ban Nha",
        "Tây ban nha":"Tây Ban Nha",
        "bồ đào nha":"Bồ Đào Nha",
        "Bồ đào nha":"Bồ Đào Nha",
        "hà lan":"Hà Lan",
        "Hà lan":"Hà Lan",
        "bỉ":"Bỉ",
        "đan mạch":"Đan Mạch",
        "Đan mạch":"Đan Mạch",
        "hy lạp":"Hy Lạp",
        "Hy lạp":"Hy Lạp",
        "ukraine":"Ukraine",
        "bulgaria":"Bulgaria",
        "romania":"Romania",
        "iceland":"Iceland",
        "ai cập":"Ai Cập",
        "Ai cập":"Ai Cập",
        "lybia":"Lybia",
        "nam phi":"Nam Phi",
        "algeria":"Algeria",
        "maroc":"Maroc",
        "cameroon":"Cameroon",
        "nigeria":"Nigeria",
        "togo":"Togo",
        "ghana":"Ghana",
        "gambia":"Gambia",
        "angola":"Angola",
        "brazil":"Brazil",
        "canada":"Canada",
        "mexico":"Mexico",
        "hoa kỳ":"Hoa Kỳ",
        "Hoa kỳ":"Hoa Kỳ",
        "costa rica":"Costa Rica",
        "colombia":"Colombia",
        "ecuador":"Ecuador",
        "peru":"Peru",
        "chile":"Chile",
        "argentina":"Argentina",
        "paraguay":"Paraguay",
        "uruguay":"Uruguay",
        "cuba":"Cuba",
        "tokyo":"Tokyo",
        "osaka":"Osaka",
        "kanagawa":"Kanagawa",
        "aichi":"Aichi",
        "saitama":"Saitama",
        "chiba":"Chiba",
        "hokkaidō":"Hokkaidō",
        "hyogo":"Hyogo",
        "fukuoka":"Fukuoka",
        "shizuoka":"Shizuoka",
        "ibaraki":"Ibaraki",
        "hiroshima":"Hiroshima",
        "kyoto":"Kyoto",
        "niigata":"Niigata",
        "miyagi":"Miyagi",
        "nagano":"Nagano",
        "gifu":"Gifu",
        "fukushima":"Fukushima",
        "gunma":"Gunma",
        "tochigi":"Tochigi",
        "okayama":"Okayama",
        "mie":"Mie",
        "kumamoto":"Kumamoto",
        "kagoshima":"Kagoshima",
        "yamaguchi":"Yamaguchi",
        "nagasaki":"Nagasaki",
        "ehime":"Ehime",
        "aomori":"Aomori",
        "nara":"Nara",
        "iwate":"Iwate",
        "shiga":"Shiga",
        "okinawa":"Okinawa",
        "yamagata":"Yamagata",
        "ōita":"Ōita",
        "ishikawa":"Ishikawa",
        "akita":"Akita",
        "miyazaki":"Miyazaki",
        "toyama":"Toyama",
        "wakayama":"Wakayama",
        "kagawa":"Kagawa",
        "yamanashi":"Yamanashi",
        "saga":"Saga",
        "fukui":"Fukui",
        "tokushima":"Tokushima",
        "kochi":"Kochi",
        "shimane":"Shimane",
        "tottori":"Tottori",
        "new zealand":"New Zealand",
        "New zealand":"New Zealand",
        "an giang":"An Giang",
        "An giang":"An Giang",
        "bà rịa":"Bà Rịa",
        "Bà rịa":"Bà Rịa",
        "vũng tàu":"Vũng Tàu",
        "bắc cạn":"Bắc Cạn",
        "bắc giang":"Bắc Giang",
        "bạc liêu":"Bạc Liêu",
        "bắc ninh":"Bắc Ninh",
        "bến tre":"Bến Tre",
        "bình định":"Bình Định",
        "bình dương":"Bình Dương",
        "bình phước":"Bình Phước",
        "bình thuận":"Bình Thuận",
        "cà mau":"Cà Mau",
        "cao bằng":"Cao Bằng",
        "cần thơ":"Cần Thơ",
        "đà nẵng":"Đà Nẵng",
        "đắk lắk":"Đắk Lắk",
        "đắk nông":"Đắk Nông",
        "điện biên":"Điện Biên",
        "đồng nai":"Đồng Nai",
        "đồng tháp":"Đồng Tháp",
        "gia lai":"Gia Lai",
        "hà giang":"Hà Giang",
        "hà nam":"Hà Nam",
        "hà nội":"Hà Nội",
        "Hà nội":"Hà Nội",
        "hà tĩnh":"Hà Tĩnh",
        "hải dương":"Hải Dương",
        "hải phòng":"Hải Phòng",
        "hậu giang":"Hậu Giang",
        "hồ chí minh":"Hồ Chí Minh",
        "hòa bình":"Hòa Bình",
        "hưng yên":"Hưng Yên",
        "khánh hòa":"Khánh Hòa",
        "kiên giang":"Kiên Giang",
        "kon tum":"Kon Tum",
        "lai châu":"Lai Châu",
        "lâm đồng":"Lâm Đồng",
        "lạng sơn":"Lạng Sơn",
        "lào cai":"Lào Cai",
        "long an":"Long An",
        "nam định":"Nam Định",
        "nghệ an":"Nghệ An",
        "ninh bình":"Ninh Bình",
        "ninh thuận":"Ninh Thuận",
        "phú thọ":"Phú Thọ",
        "phú yên":"Phú Yên",
        "quảng bình":"Quảng Bình",
        "quảng nam":"Quảng Nam",
        "quảng ngãi":"Quảng Ngãi",
        "quảng ninh":"Quảng Ninh",
        "quảng trị":"Quảng Trị",
        "sóc trăng":"Sóc Trăng",
        "sơn la":"Sơn La",
        "tây ninh":"Tây Ninh",
        "thái bình":"Thái Bình",
        "thái nguyên":"Thái Nguyên",
        "thanh hóa":"Thanh Hóa",
        "thừa thiên huế":"Thừa Thiên Huế",
        "tiền giang":"Tiền Giang",
        "trà vinh":"Trà Vinh",
        "tuyên quang":"Tuyên Quang",
        "vĩnh long":"Vĩnh Long",
        "vĩnh phúc":"Vĩnh Phúc",
        "yên bái":"Yên Bái"
    }

    POS_name_en = {
        "vietnam":"VietNam",
        "vietnamese":"Vietnamese",
        "thailan":"ThaiLan",
        "myanmar":"Myanmar",
        "malaysia":"Malaysia",
        "philippines":"Philippines",
        "indonesia":"Indonesia",
        "cambodia":"Cambodia",
        "denmark":"Denmark",
        "brunei":"Brunei",
        "singapore":"Singapore",
        "spain":"Spain",
        "japan":"Japan",
        "japanese":"Japanese",
        "south korea":"South Korea",
        "sweden":"Sweden",
        "switzerland":"Switzerland",
        "china":"China",
        "chinese":"Chinese",
        "uzebekistan":"Uzebekistan",
        "india":"India",
        "afganistan":"Afganistan",
        "australia":"Australia",
        "iran":"Iran",
        "iraq":"Iraq",
        "israel":"Israel",
        "jordan":"Jordan",
        "liban":"Liban",
        "oman":"Oman",
        "pakistan":"Pakistan",
        "qatar":"Qatar",
        "english":"English",
        "england":"England",
        "germany":"Germany",
        "greece":"Greece",
        "france":"France",
        "french":"French",
        "paris":"Paris",
        "portugal":"Portugal",
        "poland":"Poland",
        "london":"London",
        "new york":"New York",
        "italia":"Italia",
        "russian":"Russian",
        "ukraine":"Ukraine",
        "bulgaria":"Bulgaria",
        "romania":"Romania",
        "iceland":"Iceland",
        "lybia":"Lybia",
        "algeria":"Algeria",
        "maroc":"Maroc",
        "turkey":"Turkey",
        "cameroon":"Cameroon",
        "nigeria":"Nigeria",
        "togo":"Togo",
        "ghana":"Ghana",
        "gambia":"Gambia",
        "angola":"Angola",
        "brazil":"Brazil",
        "canada":"Canada",
        "mexico":"Mexico",
        "america":"America",
        "american":"America",
        "costa rica":"Costa Rica",
        "colombia":"Colombia",
        "ecuador":"Ecuador",
        "peru":"Peru",
        "chile":"Chile",
        "argentina":"Argentina",
        "paraguay":"Paraguay",
        "uruguay":"Uruguay",
        "cuba":"Cuba",
        "tokyo":"Tokyo",
        "osaka":"Osaka",
        "kanagawa":"Kanagawa",
        "aichi":"Aichi",
        "saitama":"Saitama",
        "chiba":"Chiba",
        "hokkaidō":"Hokkaidō",
        "hyogo":"Hyogo",
        "fukuoka":"Fukuoka",
        "shizuoka":"Shizuoka",
        "ibaraki":"Ibaraki",
        "hiroshima":"Hiroshima",
        "kyoto":"Kyoto",
        "niigata":"Niigata",
        "miyagi":"Miyagi",
        "nagano":"Nagano",
        "gifu":"Gifu",
        "fukushima":"Fukushima",
        "gunma":"Gunma",
        "tochigi":"Tochigi",
        "okayama":"Okayama",
        "mie":"Mie",
        "kumamoto":"Kumamoto",
        "kagoshima":"Kagoshima",
        "yamaguchi":"Yamaguchi",
        "nagasaki":"Nagasaki",
        "ehime":"Ehime",
        "aomori":"Aomori",
        "nara":"Nara",
        "iwate":"Iwate",
        "shiga":"Shiga",
        "okinawa":"Okinawa",
        "yamagata":"Yamagata",
        "ōita":"Ōita",
        "ishikawa":"Ishikawa",
        "akita":"Akita",
        "miyazaki":"Miyazaki",
        "toyama":"Toyama",
        "wakayama":"Wakayama",
        "kagawa":"Kagawa",
        "yamanashi":"Yamanashi",
        "saga":"Saga",
        "fukui":"Fukui",
        "tokushima":"Tokushima",
        "kochi":"Kochi",
        "shimane":"Shimane",
        "tottori":"Tottori",
        "new zealand":"New Zealand",
        "marrakesh":"Marrakesh",
        "manila":"Manila",
        "montreal":"Montreal",
        "moscow":"Moscow",
        "mumbai":"Mumbai",
        "nairobi":"Nairobi",
        "New delhi":"New Delhi",
        "new delhi":"New Delhi",
        "nicosia":"Nicosia",
        "oslo":"Oslo",
        "ottawa":"Ottawa",
        "rome":"Rome",
        "Saint petersburg":"Saint Petersburg",
        "saint petersburg":"Saint Petersburg",
        "San francisco":"San Francisco",
        "san francisco":"San Francisco",
        "santiago":"Santiago",
        "seoul":"Seoul",
        "shanghai":"Shanghai",
        "sofia":"Sofia",
        "stockholm":"Stockholm",
        "sydney":"Sydney",
        "tallinn":"Tallinn",
        "tehran":"Tehran",
        "toronto":"Toronto",
        "venice":"Venice",
        "vienna":"Vienna",
        "vilnius":"Vilnius",
        "warsaw":"Warsaw",
        "washington":"Washington",
        "wellington":"Wellington",
        "zagreb":"Zagreb",
        "amsterdam":"Amsterdam",
        "athens":"Athens",
        "baghdad":"Baghdad",
        "bangkok":"Bangkok",
        "barcelona":"Barcelona",
        "beijing":"Beijing",
        "belgrade":"Belgrade",
        "berlin":"Berlin",
        "bogota":"Bogota",
        "bratislava":"Bratislava",
        "brussels":"Brussels",
        "bucharest":"Bucharest",
        "budapest":"Budapest",
        "Buenos aires":"Buenos Aires",
        "buenos aires":"Buenos Aires",
        "cairo":"Cairo",
        "Cape town":"Cape Town",
        "cape town":"Cape Town",
        "caracas":"Caracas",
        "chicago":"Chicago",
        "copenhagen":"Copenhagen",
        "dhaka":"Dhaka",
        "dubai":"Dubai",
        "dublin":"Dublin",
        "frankfurt":"Frankfurt",
        "geneva":"Geneva",
        "hanoi":"Hanoi",
        "helsinki":"Helsinki",
        "Hong kong":"Hong Kong",
        "hong kong":"Hong Kong",
        "istanbul":"Istanbul",
        "jakarta":"Jakarta",
        "jerusalem":"Jerusalem",
        "johannesburg":"Johannesburg",
        "kabul":"Kabul",
        "karachi":"Karachi",
        "kiev":"Kiev",
        "Kuala lumpur":"Kuala Lumpur",
        "kuala lumpur":"Kuala Lumpur",
        "lagos":"Lagos",
        "lahore":"Lahore",
        "lima":"Lima",
        "lisbon":"Lisbon",
        "ljubljana":"Ljubljana",
        "london":"London",
        "Los angeles":"Los Angeles",
        "los angeles":"Los Angeles",
        "luxembourg":"Luxembourg",
        "madrid":"Madrid"
    }
